### ISSUE TITLE
commit number of Pytorch you built from source

### ISSUE THREAD

**Issue by msr-peng** [Kolkir/mlcpp#13]
Hey Kolkir, I'm trying to reproduce your demo of Mask RCNN. After i downloaded the latest Pytorch from GitHub, and built its library from source. I found the mask rcnn demo can be compiled and built successfully, but can not run. It seems that the latest Pytorch is now incompatible with your mask rcnn implementation. Could you provide me the exact Pytorch commit number when you build it from source? So I can use the exact same Pytorch with you.

**Comment by msr-peng** [comment]
If you don't know the commit number of the Pytorch repository, a approximate day when you download pytorch repository is also ok.

**Comment by Kolkir** [comment]
Hello, last time I've built and ran demo with PyTorch v1.0.1 (commit hash 83221655a8237ca80f9673dad06a98d34c43e546)

**Comment by msr-peng** [comment]
> Hello, last time I've built and ran demo with PyTorch v1.0.1 (commit hash 83221655a8237ca80f9673dad06a98d34c43e546)

Thanks for your quick reply. It works now!

**Comment by msr-peng** [comment]
> Hello, last time I've built and ran demo with PyTorch v1.0.1 (commit hash 83221655a8237ca80f9673dad06a98d34c43e546)

Hey Kolkir, I really thank you for your C++ implementation of MaskRCNN. I just finished my own robotics project (https://github.com/msr-peng/maskfusion_cpp) which is based on your work!
