### ISSUE TITLE
cannt open source file curl/curl.h 

### ISSUE THREAD

**Issue by oumingyang** [Kolkir/mlcpp#22]
Hi, Thanks for your code.  I got a problem on the utils.cpp  when i build the "Machine Learning with C++ - Polynomial regression with Eigen" in vscode + cmake. It reports "cannt open source file curl/curl.h ". I guess the curl-lib maybe one of your personal lib, or is that a open-source lib:https://github.com/curl/curl?

**Comment by Kolkir** [comment]
@oumingyang Hello, I mentioned that I used `libcurl` library in the previous articles. Yes, you are right the https://github.com/curl/curl repository contains sources for this library. But I installed it from a package manager in the Arch Linux, and I pretty sure that it can be easily installed in the same way on any Linux distribution.
