### ISSUE TITLE
rpn and anchor generator seem error

### ISSUE THREAD

**Issue by rockyzhengwu** [Kolkir/mlcpp#23]
https://github.com/Kolkir/mlcpp/blob/afb08c0c81bdd2c68710831e8d4b233005ab3750/mask_rcnn_pytorch/anchors.cpp#L63

this function should change to below , because should  iterator on feature map not the anchor scale  size;
```c++
torch::Tensor GeneratePyramidAnchors(
    std::vector<float> scales_vec,
    std::vector<float> ratios_vec,
    const std::vector<std::pair<float, float> >& feature_shapes,
    const std::vector<float>& feature_strides,
    float anchor_stride) {
      std::vector<at::Tensor> anchors;
      auto ratios = torch::tensor(ratios_vec);
      auto scales = torch::tensor(scales_vec);
      for (size_t i = 0; i < feature_strides.size(); ++i) {
       anchors.push_back(GenerateAnchors(scales, ratios, feature_shapes[i],
                                      feature_strides[i], anchor_stride));
  }
  return torch::cat(anchors, /*dim*/ 0);
```

**Comment by rockyzhengwu** [comment]
https://github.com/Kolkir/mlcpp/blob/afb08c0c81bdd2c68710831e8d4b233005ab3750/mask_rcnn_pytorch/maskrcnn.cpp#L554

i'm not sure about this , may be : ``` anchors_per_location = rpn_anchor_scales.size() * rpn_anchor_ratios.size()```

**Comment by Kolkir** [comment]
@rockyzhengwu Hello, your remarks look reasonable, thanks for mentioning them. For the first issue, there is a [test](https://github.com/Kolkir/mlcpp/blob/master/mask_rcnn_pytorch/tests/anchor_test.cpp) so could you please make a PR and adapt the test if it's needed. The second issue should be tested manually in runtime, did you do that?

**Comment by rockyzhengwu** [comment]
@Kolkir I made a mistake，your implementation is right, sorry about that and thanks for your reply
